trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'aksazurereader'
  resourceGroup: 'usecase-bhargav'
  aksClusterName: 'usecase-aks'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Installing kubectl..."
      az aks install-cli
  displayName: 'Install kubectl'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Getting AKS credentials..."
      az aks get-credentials --resource-group $(resourceGroup) --name $(aksClusterName)
  displayName: 'Get AKS Credentials'

- script: |
    echo "Checking node status..."
    kubectl get nodes
  displayName: 'Check Node Status'

- script: |
    echo "Checking pod status..."
    kubectl get pods --all-namespaces
  displayName: 'Check Pod Status'

- script: |
    echo "Checking cluster health..."
    kubectl get componentstatuses
  displayName: 'Check Cluster Health'

- script: |
    echo "Monitoring resource usage..."
    kubectl top nodes
    kubectl top pods --all-namespaces
  displayName: 'Monitor Resource Usage'
