trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'aksazurereader'
  resourceGroup: 'usecase-bhargav'
  aksClusterName: 'usecase-aks'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Installing kubectl..."
      az aks install-cli
  displayName: 'Install kubectl'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Getting AKS credentials..."
      az aks get-credentials --resource-group $(resourceGroup) --name $(aksClusterName)
  displayName: 'Get AKS Credentials'

- script: |
    echo "Checking node status..."
    kubectl get nodes
  displayName: 'Check Node Status'

- script: |
    echo "Checking pod status..."
    kubectl get pods --all-namespaces
  displayName: 'Check Pod Status'

- script: |
    echo "Monitoring resource usage..."
    kubectl top nodes
    kubectl top pods --all-namespaces
  displayName: 'Monitor Resource Usage'

- script: |
    echo "Generating report..."
    echo "Node Status:" > report.txt
    kubectl get nodes >> report.txt
    echo "" >> report.txt
    echo "Pod Status:" >> report.txt
    kubectl get pods --all-namespaces >> report.txt
    echo "" >> report.txt
    echo "Resource Usage:" >> report.txt
    kubectl top nodes >> report.txt
    kubectl top pods --all-namespaces >> report.txt
  displayName: 'Generate Report'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'report.txt'
    ArtifactName: 'AKSHealthReport'
  displayName: 'Publish Report'
